// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdziqrSHYb34TVuOt20kDHV2F-eSKMfc',
    appId: '1:978419317696:web:a3181ede24505296ef2625',
    messagingSenderId: '978419317696',
    projectId: 'projectott-6466b',
    authDomain: 'projectott-6466b.firebaseapp.com',
    storageBucket: 'projectott-6466b.appspot.com',
    measurementId: 'G-5EYZZFWLFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8wMsJHOupPMkP8aUUrRZ69epgSjLMXM',
    appId: '1:978419317696:android:7a26907ebe90c0eeef2625',
    messagingSenderId: '978419317696',
    projectId: 'projectott-6466b',
    storageBucket: 'projectott-6466b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7TuJ0g_c7SyxDxv_5GLuCkUxv7jb3tU',
    appId: '1:978419317696:ios:1968054042b2511aef2625',
    messagingSenderId: '978419317696',
    projectId: 'projectott-6466b',
    storageBucket: 'projectott-6466b.appspot.com',
    iosBundleId: 'com.example.otts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7TuJ0g_c7SyxDxv_5GLuCkUxv7jb3tU',
    appId: '1:978419317696:ios:1968054042b2511aef2625',
    messagingSenderId: '978419317696',
    projectId: 'projectott-6466b',
    storageBucket: 'projectott-6466b.appspot.com',
    iosBundleId: 'com.example.otts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWdziqrSHYb34TVuOt20kDHV2F-eSKMfc',
    appId: '1:978419317696:web:fd0dbb99223723ccef2625',
    messagingSenderId: '978419317696',
    projectId: 'projectott-6466b',
    authDomain: 'projectott-6466b.firebaseapp.com',
    storageBucket: 'projectott-6466b.appspot.com',
    measurementId: 'G-DWMYFJ8EN0',
  );
}
